# Generated by Django 4.1 on 2022-09-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_scoredata'),
    ]

    operations = [
        migrations.CreateModel(
            name='taskdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('scores', models.CharField(max_length=15)),
                ('date', models.CharField(max_length=15)),
            ],
        ),
    ]
